### ISSUE TITLE
initial config

### ISSUE THREAD

**Issue by orymate** [jorgen-k/signalk-autopilot-garmin#1]
Hi,

thanks for your work, I really appreciate it. I've started to do this more than once in the past, but never actually managed to make it working.

When I initially installed your plugin, it failed to load the schema and thus anything else from the plugin:

```
Mar 24 23:20:30 TypeError: Cannot read properties of undefined (reading 'properties') at plugin.schema (/data/conf/signalk/node_modules/signalk-autopilot-garmin/index.js:88:40) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:71:43 at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:88:23 at new Promise (<anonymous>) at getPluginResponseInfo (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:56:16) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:45:36 at Array.map (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:45:20 at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:144:13) at Route.dispatch (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:114:3) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:284:15 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10) at ZIP (/usr/lib/node_modules/signalk-server/node_modules/express-easy-zip/index.js:133:3)
```

Reproduction:

```
# mv /data/conf/signalk/plugin-config-data/autopilot-garmin.json{,-}
# restart signalk
# load plugin config
```

When the config file is in place and the ccuAddr is set to 2 manually, it seems to do something based on the very slight changes in the reported rudderAngle, but unfortunately I'm not at the boat. The very little change may make sense with zero speed however. I will definitely give it a try next week.

**Comment by jorgen-k** [comment]
Thanks for your input! Fix on it's way. Please continue testing and give feedback if anything is not working!

**Comment by orymate** [comment]
Thanks for the quick fix. I've just tried out  the plugin with a Garmin Reactor 40 (3.20) + GPSMap 923xsv (and no GHC). It works nice! The +/-15 degrees steering commands seem to change the course by 10 degrees though.

**Comment by jorgen-k** [comment]
Nice to hear! Good it works without GHC, i was "forced" o buy one of my retailer, claiming it was not supported with only the GPSMap. +/- 15 is a setting in the GHC, I now remember i altered that in my boat. Default is 10 degrees as you say, I will reflect this in the future. I'll open an issue on this to keep track.
Feel free to contact me here or via mail should you have any questions, comments or whishes!
